import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@mantine/core/styles.css";

import {
  Center,
  ColorSchemeScript,
  createTheme,
  MantineProvider,
} from "@mantine/core";
import Nav from "./nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  /** Put your mantine theme override here */
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body style={{ width: "100%", height: "100%", backgroundColor: "rgb(26, 26, 26)" }}>
        <MantineProvider theme={theme}>
          <Nav>
            <Center>{children}</Center>
          </Nav>
        </MantineProvider>
      </body>
    </html>
  );
}
